### ISSUE TITLE
Mod erases local score files

### ISSUE THREAD

**Issue by bodograumann** [Metalit/PlayerDataKeeper#3]
My local scores where getting lost.
I had to search for quite a while to find the root cause of this issue.
To reproduce:

- Have some existing local leaderboard file (can be empty)
- Install this mod
- Start the game
  No backup exists, so [setup()](https://github.com/Metalit/PlayerDataKeeper/blob/master/src/main.cpp#L50-L56) copies *ALL* files from the game folder to `ModData/com.beatgames.beatsaber/Mods/datakeeper`. Including (potentially empty) `LocalLeaderboards.dat` and `LocalDailyLeaderboards.dat`.
- Finish a song to have a new score added to the local leaderboard.
  During the game’s runtime, the [hook](https://github.com/Metalit/PlayerDataKeeper/blob/master/src/main.cpp#L23-L35) is called to back up new versions of `PlayerData.dat` and `settings.cfg`. It is not called for the leaderboard files however!
- Restart the game.
  On this start up the backup is found and *ALL* files from it are copied back to the actual game folder in [setup()](https://github.com/Metalit/PlayerDataKeeper/blob/master/src/main.cpp#L45-L49).
  This overwrites the leaderboards with the old data. (In my case no scores saved at all)
  The new score is gone.

*Workaround*: Manually delete  `LocalLeaderboards.dat` and `LocalDailyLeaderboards.dat` from the backup location.

I think simply not copying all the files when initially creating the backup folder in [setup()](https://github.com/Metalit/PlayerDataKeeper/blob/master/src/main.cpp#L52-L55), would prevent the issue from occuring.
Though backing up the scores correctly was probably intended and a more involved fix is needed.

This is with game version 1.24.0

**Comment by Metalit** [comment]
Thanks for investigating this. Are you sure that the hook isn't run for the leaderboard files? There isn't any filtering code, it should copy over any json file saved to the game's data location.

**Comment by Metalit** [comment]
However you are right that copying over all the files immediately isn't actually necessary and I can probably replace that with only creating the parent directory and letting files get saved with updates.
The only potential issue is that some files may not be kept if the game isn't played much but that seems to be smaller than the number of cases where restored manual files are being overwritten with blanks due to ordering issues

**Comment by bodograumann** [comment]
Pretty sure about what I found. Tested multiple times and even after removing the empty backed up files, they are not saved via the hook.
Maybe for those files a new method is used in 1.24 instead of SaveToJSONFile. Not sure how to tell though.

**Comment by Metalit** [comment]
You're right, it uses a different method to save the JSON for some reason. I'll add a hook to catch them as well
