### ISSUE TITLE
el fichero no se puede descargar da error 404 esta pagina no exite

### ISSUE THREAD

**Issue by Xiscotrisca** [Metalit/PlayerDataKeeper#5]
Buenos dias, necesito descargar este fichero desde la pagina de beat saber mods y no funciona el enlace de descarga, gracias un saludo

**Comment by Metalit** [comment]
There was an issue with the link to the latest version as I had modified the release action. It should be resolved for 1.26.1, I'm not sure if anything will be done for 1.26.0 as it's unlikely any other mods will release for that version.

**Comment by Xiscotrisca** [comment]
Muchas gracias por todo tú trabajo, un saludo.
Enviado desde Yahoo Mail con Android 
 
  El dom., dic. 4, 2022 a 18:16, ***@***.***> escribió:   


There was an issue with the link to the latest version as I had modified the release action. It should be resolved for 1.26.1, I'm not sure if anything will be done for 1.26.0 as it's unlikely any other mods will release for that version.
