### ISSUE TITLE
URL mismatch with mods.json

### ISSUE THREAD

**Issue by L3Home** [Metalit/PlayerDataKeeper#8]
Just FYI... the version 1.26.2 mods.json (which I found on the GUI briefly but has disappeared again) lists the URLs for two of your mods incorrectly (so they 404).

PlayerDataKeeper's version for 1.26.2: the github release is named https://github.com/Metalit/PlayerDataKeeper/releases/tag/v0.1.5 but the json link is listed without the "v" as just "0.1.5"

PlaylistCore is also affected, but the reverse is true; the github release is named https://github.com/Metalit/PlaylistCore/releases/tag/1.1.3 without a "v" in its name, but the mods.json list shows up as "v1.1.3"

Your other core mod(s) are fine. I don't know about the non-core ones though, since there seems to be an issue with the version in the dropdown list and the json. I *swear* I saw 1.26.2 or 1.26.1 on that dropdown list and viewed all the core mods there (I was excited to see the update, and downloaded all of the core mods) but just as quickly, it disappeared again. The proof is that I know about your 2 links being backwards; after all, the release version numbers aren't the same between 1.25 and 1.26. I don't know if ComputerElite is working on his/her files right now but suspect that's the case.

Anyway, I hope this helps! And thank you for all of the time you (and other mod authors) spend on these; they DO make the game better!

**Comment by Metalit** [comment]
Old issue and resolved but I never closed it whoops
